name: Cross-Compile Masscan for Windows test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout masscan repository
        uses: actions/checkout@v3
        with:
          repository: robertdavidgraham/masscan
          ref: master

      - name: Set up cross-compilation environment
        run: |
          sudo apt-get update
          sudo apt-get install -y mingw-w64

      - name: Cross-compile Masscan
        run: |
          make CC=x86_64-w64-mingw32-gcc

      - name: Archive executable
        run: |
          mkdir dist
          cp masscan.exe dist/
          zip -r masscan.zip dist/

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: masscan-windows
          path: masscan.zip
