name: Build masscan.exe

on:
  workflow_dispatch:  # Запуск вручную через GitHub UI
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up MSYS2 and MinGW
      uses: msys2/setup-msys2@v2
      with:
        update: true
        install: |
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-make
          git

    - name: Download Npcap SDK
      shell: powershell
      run: |
        $sdkUrl = "https://npcap.com/dist/npcap-sdk-1.13.zip"
        Invoke-WebRequest -Uri $sdkUrl -OutFile "npcap-sdk.zip"
        Expand-Archive -Path "npcap-sdk.zip" -DestinationPath "npcap-sdk"

    - name: Build masscan.exe
      shell: msys2 {0}
      env:
        PATH: /mingw64/bin:$PATH  # Ключевое исправление
        C_INCLUDE_PATH: ${{ github.workspace }}/npcap-sdk/Include
        LIBRARY_PATH: ${{ github.workspace }}/npcap-sdk/Lib/x64
      run: |
        make

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: masscan.exe
        path: masscan.exe
